<a href="https://colab.research.google.com/github/ABINAYA600/DL_LAB/blob/main/DL_program_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q gymnasium

In [1]:
import gymnasium as gym
import numpy as np


# =====================================================
# Create FrozenLake environment
# =====================================================

env = gym.make(
    "FrozenLake-v1",
    is_slippery=True
)


# =====================================================
# Q-learning parameters
# =====================================================

learning_rate = 0.1
discount_factor = 0.99

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01

decay_rate = 0.005


# =====================================================
# Get state and action size
# =====================================================

state_size = env.observation_space.n
action_size = env.action_space.n


print("Number of states:", state_size)
print("Number of actions:", action_size)


# =====================================================
# Initialize Q-table
# =====================================================

q_table = np.zeros(
    (state_size, action_size)
)


# =====================================================
# Training parameters
# =====================================================

num_episodes = 10000
max_steps = 100


# =====================================================
# TRAINING
# =====================================================

for episode in range(num_episodes):

    # Reset environment
    state, info = env.reset()

    for step in range(max_steps):

        # -------------------------------------------------
        # Epsilon-greedy action selection
        # -------------------------------------------------

        if np.random.uniform(0, 1) < epsilon:

            # Exploration
            action = env.action_space.sample()

        else:

            # Exploitation
            action = np.argmax(
                q_table[state, :]
            )


        # -------------------------------------------------
        # Take action
        # -------------------------------------------------

        new_state, reward, terminated, truncated, info = env.step(
            action
        )


        # -------------------------------------------------
        # Update Q-table
        # -------------------------------------------------

        q_table[state, action] = (
            q_table[state, action]
            + learning_rate
            * (
                reward
                + discount_factor
                * np.max(q_table[new_state, :])
                - q_table[state, action]
            )
        )


        # Move to new state
        state = new_state


        # Check whether episode ended
        if terminated or truncated:
            break


    # -----------------------------------------------------
    # Decay epsilon
    # -----------------------------------------------------

    epsilon = (
        min_epsilon
        + (max_epsilon - min_epsilon)
        * np.exp(-decay_rate * episode)
    )


# =====================================================
# Display learned Q-table
# =====================================================

print("\nTraining completed!")

print("\nQ-Table:")
print(q_table)


# =====================================================
# TESTING
# =====================================================

num_test_episodes = 100

total_rewards = 0


for episode in range(num_test_episodes):

    state, info = env.reset()

    episode_rewards = 0


    for step in range(max_steps):

        # Choose best action
        action = np.argmax(
            q_table[state, :]
        )


        # Take action
        new_state, reward, terminated, truncated, info = env.step(
            action
        )


        # Add reward
        episode_rewards += reward


        # Move to next state
        state = new_state


        # Stop if episode ends
        if terminated or truncated:
            break


    total_rewards += episode_rewards


# =====================================================
# Calculate average reward
# =====================================================

average_reward = (
    total_rewards / num_test_episodes
)


print(
    "\nAverage reward over",
    num_test_episodes,
    "test episodes:",
    average_reward
)


# Close environment
env.close()

Number of states: 16
Number of actions: 4

Training completed!

Q-Table:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Average reward over 100 test episodes: 0.0
